---
title: "lab4_moduleB"
author: "Drew Walker"
date: "11/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tm)
library(caTools)
library(rfUtilities)
library(e1071)
library(caTools)

```

```{r dataload}
full_dataset <- read_csv("Tweets.csv")

tweet_texts <- full_dataset$text

tweet_corpus <- VCorpus(VectorSource(tweet_texts))
```
# preprocessing
```{r preprocess}
myStopWords <- c(stopwords())
corpus <- tweet_corpus %>% 
  tm_map(content_transformer(tolower)) %>% 
  tm_map(removePunctuation) %>% 
  tm_map(removeWords,myStopWords) %>% 
  tm_map(stemDocument)
length(corpus)
```

```{r split-avoid-leak}
NLP_tokenizer <- function(x){
  unlist(lapply(ngrams(words(x),1:3),paste,collapse = "_"),use.names=FALSE)
}
n_gram_corpus <- tm_map(corpus,content_transformer(NLP_tokenizer))
```

View length of corpus and content to ensure ngrams generated properly

```{r, viewlength}
length(n_gram_corpus)
n_gram_corpus[[2]]$content
```


## Creating ttraining and test data for ML
```{r creating-training-and-test}

set.seed(1234)
split = sample.split(full_dataset$airline_sentiment, SplitRatio = 0.8)
training_ngram_corpus = subset(n_gram_corpus, split==TRUE)

eval_n_gram_corpus = subset(n_gram_corpus,split==FALSE)

training_classes <- subset(full_dataset$airline_sentiment,split==TRUE)
eval_classes <- subset(full_dataset$airline_sentiment,split==FALSE)
```

# Vectorize
```{r create-dtm}
training_dtm <- DocumentTermMatrix(training_ngram_corpus)
training_dtm_sparse <- removeSparseTerms(training_dtm,0.995)
```

# restricting columns for test set
```{r, restricting}
eval_dtm_sparse <- DocumentTermMatrix(eval_n_gram_corpus,list(dictionary=colnames(training_dtm_sparse)))
```

```{r dataframes}
training_dtm_df <- as.data.frame(as.matrix(training_dtm_sparse))
eval_dtm_df <- as.data.frame(as.matrix(eval_dtm_sparse))
colnames(training_dtm_df) <- make.names(colnames(training_dtm_df))
colnames(eval_dtm_df) <- make.names(colnames(eval_dtm_df))

training_dtm_df$airline_sentiment <- training_classes
training_dtm_df$airline_sentiment <- as.factor(training_dtm_df$airline_sentiment)
```


```{r svm}
trained_model <- svm(airline_sentiment ~.,data=training_dtm_df)
```


```{r predictions}
predictions <- predict(trained_model, newdata=eval_dtm_df)
```


# Accuracy
```{r, warning=FALSE}


accuracy(eval_classes,predictions)
```

